services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      api-tests:
        condition: service_completed_successfully
  api-tests:
    build:
      dockerfile: Dockerfile_test